@startuml
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRManager
participant ":System" as System

activate HRManager

HRManager -> System : Requests team generation for a task
activate System

    System --> HRManager : Requests for data(skills needed, min size, max size of the team)
    deactivate System

    HRManager -> System : Provides data
    activate System

    System --> HRManager : Confirms data reception and presents options (Approve, Reject)
    deactivate System

    HRManager -> System : Submits selection (Approve/Reject)
    activate System

    alt Reject
        loop until approved
            System --> HRManager : Declines team approval and generates new team
            HRManager -> System : Submits selection (Approve/Reject)
        end
    else Approve
        System --> HRManager : Confirms team approval
    end

deactivate System

@enduml