@startuml

hide methods
hide circle
hide empty attributes
skinparam linetype polyline


class Employee {
}

class Tasks {
  - taskCategory
  - toDoList
}

class Agenda {
}

Employee "1"---"0..*" Tasks: manages >
Agenda "1"---"1..*" Tasks : organizes >

@enduml
