@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US25

autonumber

actor "Green Space Manager \nManager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : list GSM tasks
    activate System

        System --> GSM : list task, ask to select task to be cancelled
    deactivate System

    GSM -> System : types requested data
    activate System

        System --> GSM : shows all data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

        System --> GSM : displays operation success
    deactivate System

@enduml