@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US29 - As a Collaborator, I want to record the completion of a task\nSystem Sequence Diagram (SSD)

autonumber

actor "Collaborator" as User
participant ":System" as System

activate User

    User -> System : requests to mark a task as completed
    activate System

        System --> User : list collaborator tasks in schedule
    deactivate System

    User -> System : selects tasks from the list
    activate System

    System --> User : display tasks details and requests confirmation
        deactivate System

    User -> System : confirms task completion
        activate System

    System --> User : success in recording task completion


    deactivate System



@enduml
