@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 - As a Human Resources Manager (HRM), I want to register skills that a collaborator may have\nSystem Sequence Diagram (SSD)

autonumber

actor "Human Resources Manager\n(HRM)" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new skill
    activate System

        System --> Employee : requests data (Name the skill)
    deactivate System

    Employee -> System : types requested data (Skill name)
    activate System

    System --> Employee : shows all data and requests confirmation
        deactivate System

        Employee -> System : confirms data
        activate System

        System --> Employee : displays operation success
    deactivate System

@enduml