@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources Manager\n(HRM)" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a assign one skill or more to a collaborator
    activate System

        System --> Employee : requests data (which collaborator?)
    deactivate System

    Employee -> System : name the collaborator
    activate System

        System --> Employee : shows task category list and asks to select one
    deactivate System

    Employee -> System : selects a task category
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml