@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US020 - Register a Green Space\nSystem Sequence Diagram (SSD)

autonumber

actor "Green Space Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests to register a new green space
    activate System

        System --> GSM : requests data (types Name, select Size classification, type Area, type Address)
    deactivate System

    GSM -> System : types/ selects requested data
    activate System

        System --> GSM : Show green space data and request confirmation
        deactivate System

        GSM -> System : confirms data
        activate System

        System --> GSM : displays operation success
        
    deactivate System

@enduml
