@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US021 - Add a New Entry to the To-Do List\nSystem Sequence Diagram (SSD)

autonumber

actor "Green Space Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests to add a new To-Do List entry
    activate System

        System --> GSM : requests data (Title, Description, Green Space, Degree of Urgency, Expected Duration)
    deactivate System

    GSM -> System : types requested data (selects Green Space,degree of urgency, and Title from a list, types the rest of the data)
    activate System

        System --> GSM : Show To-Do List entry data and request confirmation
        deactivate System

        GSM -> System : confirms data
        activate System

        System --> GSM : displays operation success
        
    deactivate System

@enduml
