@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class HRM {
}

class Skills {
  - name
}


Skills "1..*"---"1" HRM : created by >
Employee "1"---"1" HRM : is a >

@enduml