@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CreateSkillUI {
}

class CreateSkillController {
    - SkillRepository skillRepository
    + CreateSkillController(skillRepository: SkillRepository)
    + createSkill(skillName: String): void
}

class Repositories {
    - Repositories()
    + getInstance(): Repositories
    + getSkillRepository(): SkillRepository
}

class SkillRepository {
    'Retorna uma skill com base no seu nome
    + getSkillByName(skillName: String): Skill
    'Cria uma nova skill e a adiciona ao repositório
    + createSkill(skillName: String): Skill
    'Remove uma skill do repositório
    + deleteSkill(skillId: String): void
}

class Skill {
    - String name
    + Skill(name: String)
}

CreateSkillUI ---> CreateSkillController
CreateSkillController ---> Repositories
CreateSkillController ---> SkillRepository
SkillRepository ---> Skill
CreateSkillController .> Repositories : repositories
CreateSkillController .> SkillRepository : skillRepository
CreateSkillController .> Skill : skill

@enduml