@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US023


autonumber

actor "Green Space Manager\n(GSM)" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to assign a team to a task
    activate System

        System --> GSM : requests data (Team and Task details)
    deactivate System

    GSM -> System : provides requested data (Team and Task details)
    activate System


        System --> GSM : shows all data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

        System --> GSM : displays operation success
    deactivate System

deactivate GSM

@enduml


