@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources Manager\n(HRM)" as Employee
participant ":System" as System

activate Employee

    Employee -> System : List for a collaborator available
    activate System

        System --> Employee : Shows list of collaborators
    deactivate System

    Employee -> System : Choose collaborator
    activate System

        System --> Employee : Shows skills list, asks to select one or more
    deactivate System

    Employee -> System : Selects one or more skills
    activate System

        System --> Employee : Shows all data and requests confirmation
    deactivate System

    Employee -> System : Confirms collaborator and skill assigned
    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml