@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US028 - As a Collaborator, I wish to consult the tasks assigned to me between two dates\nSystem Sequence Diagram (SSD)

autonumber

actor "Collaborator" as Collaborator
participant ":System" as System

activate Collaborator

    Collaborator -> System : requests to view tasks between two dates
    activate System

        System --> Collaborator : requests email, start date, end date and task status
    deactivate System

    Collaborator -> System : provides email, start date, end date and task status
    activate System


         System --> Collaborator : shows email, start date, end date and task status
    deactivate System

    Collaborator -> System : confirm data (email, start date, end date and task status)
    activate System


        System --> Collaborator : displays list of tasks sorted by date and filtered by status
    deactivate System

deactivate Collaborator


@enduml
