@startuml

skinparam class {
    BackgroundColor #FEFECE
    ArrowColor #3498db
    BorderColor #2ecc71
}

skinparam classAttributeIconSize 0

class User {
}

class Parque {
}

class Organization {
}

class Admin {
}

class Employee {
}

class Job {
}

class Skill {
}

class Team {
}

class Vehicle {
}

class Schedule {
}

class Task {
}

class Tool {
}

class Machine {
}

' Relationships
User -down-> Parks : uses
Parks -down-> Organization : belongs to
Organization -down-> Admin : managed by
Admin -down-> Employee : is a >
Admin -down-> Job : assigns >
Admin -down-> Skill : regists >
Admin -down-> Team : organizes >
Admin -down-> Vehicle : operates >
Job -[hidden]-> Skill
Skill -[hidden]-> Team
Team -[hidden]-> Vehicle
Job -left-> Employee : performed by >
Skill -left-> Employee : possesses >
Employee -right-> Team : part of >
Team -right-> Vehicle : uses
Team -right-> Tool : uses >
Team -right-> Machine : operates >
Admin -right-> Schedule : plans >
Schedule -right-> Task : organize >
Task -up-> Parks : involves

' Layout adjustments
User -[hidden]- Parks
Parks -[hidden]- Organization
Organization -[hidden]- Admin
Admin -[hidden]- Employee
Employee -[hidden]- Job
Job -[hidden]- Skill
Skill -[hidden]- Team
Team -[hidden]- Vehicle
Vehicle -[hidden]- Schedule
Schedule -[hidden]- Task
Task -[hidden]- Tool
Tool -[hidden]- Machine

@enduml
