@startuml

class Organization {
}


class Collaborator {
  - name 
  - id 
}

class HRM {
}

class GSM {
}

class VFM {
}

class Job {
  - description
  - skillsAssigned
}

class Skills {
  - name 
}

class Teams {
  - numElements 
  - skillsNeeded
}

class Tasks {
  - taskCategory 
}

class Agenda {
  
}

class Malfunctions {
  - description 
  - reportedDate 
}

class GreenSpaces {
  - type 
}

class Equipment {
  - description 
}

class Vehicles {
  - brand 
  - model 
  - type 
  - tareWeight 
  - grossWeight 
  - currentKms 
  - registrationDate
  - acquisitionDate 
  - maintenanceFrequency 
}

class Machines {
  - description 
}

class GSU {
}

class Portal {
}

class Faults {
  - description 
  - reportedDate
}

class Agenda {
}

Organization --> Collaborator

Collaborator --> HRM : "is"
Collaborator --> GSM : "is"
Collaborator --> VFM : "is"
Collaborator ---> Teams

HRM --- Teams
HRM ---> Skills
HRM ---> Job

GSM ---> Agenda
GSM ---> Tasks

Agenda ---> Tasks : "Shedule"


VFM ---> Vehicles
VFM ---> Machines
VFM ---> Equipment

Job ---> Collaborator

Skills ---> Collaborator
Skills ---> Teams
Skills --> Tasks

Vehicles ---> Tasks
Machines ---> Tasks
Equipment ---> Tasks

Teams ---> Skills
Teams ---> Tasks

GSU ---> Portal
GSU ---> GreenSpaces

Portal ---> Malfunctions
Portal ---> Comments
Portal ---> Faults

Tasks ---> GreenSpaces
Tasks ---> Skills














@enduml
