@startuml

class Organization {
}

class Employee {
}

class Collaborator {
  - name 
  - id 
}

class HRM {
}

class GSM {
}

class VFM {
}

class Job {
  - description
  - skillsAssigned
}

class Skills {
  - name 
}

class Teams {
  - numElements 
  - skillsNeeded
}

class Tasks {
  - taskCategory 
}

class Agenda {
  
}

class Malfunctions {
  - description 
  - reportedDate 
}

class GreenSpaces {
  - type 
}

class Equipment {
  - description 
}

class Vehicles {
  - brand 
  - model 
  - type 
  - tareWeight 
  - grossWeight 
  - currentKms 
  - registrationDate
  - acquisitionDate 
  - maintenanceFrequency 
}

class Machines {
  - description 
}

class GSU {
}

class Portal {
}

class Faults {
  - description 
  - reportedDate
}


Organization --> Employee : "employs"

Employee --> Collaborator : "is"
Employee --> HRM : "is"
Employee --> GSM : "is"
Employee --> VFM : "is"

Collaborator --> HRM : "managed by"
Collaborator --> Job : "has"
Collaborator --> Skills : "possesses"
Collaborator --> Teams : "belongs to"

Job --> HRM : "managed by"

Skills --> HRM : "managed by"
Skills --> Teams : "utilized in"

Teams --> Tasks : "assigned"

GSM --> Agenda : "manages"
GSM --> Tasks : "manages"
GSM --> Malfunctions : "manages"

Agenda --> Tasks : "schedules"

Tasks --> GreenSpaces : "relates to"
Tasks --> Equipment : "utilizes"
Tasks --> Vehicles : "utilizes"
Tasks --> Machines : "utilizes"

VFM --> Vehicles : "maintains"
VFM --> Machines : "maintains"
VFM --> Equipment : "maintains"

GSU --> Portal : "utilizes"
Portal --> Malfunctions : "reports"
Portal --> Faults : "reports"
GSU --> GreenSpaces : "manages"

@enduml
