@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository\n:SkillRepository" as SkillRepository
participant "teamMember\n:TeamMember" as TeamMember
participant "skill\n:Skill" as Skill

activate ADM

    ADM -> UI : asks to assign a skill to a collaborator
    activate UI

    UI --> ADM : requests data (collaborator ID, skill ID)
    deactivate UI

    ADM -> UI : types requested data
    activate UI

    UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

    UI -> CTRL : assignSkillToTeamMember(teamMemberId, skillId)
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton
    CTRL <-- RepositorySingleton : Repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getSkillRepository()
    activate PLAT
    CTRL <-- PLAT : SkillRepository()
    deactivate PLAT

    CTRL -> SkillRepository : getSkillById(skillId)
    activate SkillRepository
    CTRL <-- SkillRepository : skill
    deactivate SkillRepository

    CTRL -> TeamMember : addSkill(skill)
    activate TeamMember
    CTRL <-- TeamMember : success
    deactivate TeamMember

    CTRL --> UI : success
    deactivate CTRL

    UI --> ADM : displays operation success
deactivate UI

deactivate ADM

@enduml