@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false

title US007 - System Sequence Diagram (SSD)

autonumber

actor "Vehicle and Equipment\nFleet Manager (VFM)" as VFM
participant ":System" as System

activate VFM

    VFM -> System : asks to register a new vehicle for check's up
    activate System

        System --> VFM : requests data (Vehicle ID, current km's, Check's up date)
    deactivate System

    VFM -> System : Types requested data
    activate System

        System --> VFM : Shows data and requests confirmation
    deactivate System

    VFM -> System : Confirms data
    activate System

        System --> VFM : displays operation success
    deactivate System

    deactivate System

@enduml