@startuml

hide methods
hide circle
hide empty attributes
skinparam linetype polyline


class Employee {
}

class Tasks {
  - taskCategory
  - toDoList
}

Employee "1"---"0..*" Tasks: manages >

@enduml
