@startuml

skinparam linetype polyline

hide methods
hide circle

class Employee {
}

class TeamMember {
  - name 
  - id 
}

class HRM {
}

class Skills {
  - name 
}

class Teams {
  - numElements 
  - skillsNeeded
}

Employee "1"---"1" TeamMember : is a <
Employee "1"---"0..*" Teams : manages >

TeamMember "1..*"---"1" HRM : managed by >

Skills "1..*"---"1" HRM : created by >
Skills "0..*"---"1" TeamMember : assigned to > 

@enduml