@startuml

skinparam class {
    BackgroundColor #FEFECE
    ArrowColor #3498db
    BorderColor #2ecc71
}

skinparam classAttributeIconSize 0



class HRM {
}

class Collaborator {
}

class Skill {
}

class Team {
}

HRM -down-> Collaborator : manages >
HRM -down-> Skill : needs >
HRM -down-> Team : organizes >
Skill -left-> Collaborator : possesses <
Collaborator -right-> Team : part of >




HRM -[hidden]- Collaborator
Collaborator -[hidden]- Skill
Skill -[hidden]- Team



@enduml