@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

left to right direction

class CreateVehicleUI{
}

'class Organization {
'    - vehiclesRepository: VehicleRepository
'    - name: String
'    - address: String
'    - phoneNumber: String
'}

class Vehicle {
    - plateID: String
    - brand: String
    - model: String
    - plateID: String
    - type: String
    - tare: int
    - grossWeight: int
    - current km:
    - register Date: String
    - acquisition Date: String
    - checkUpFrequencyInKms: int
    + createVehicle ()

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
    + getAuthenticationRepository()

}

class CreateVehicleController {
    + createVehicleController()
}

class VehicleRepository {
    - vehicles: List<Vehicle>
    + getVehicleByIdPlate(plateId: String): Vehicle
}



'Ligações

CreateVehicleUI ..> CreateVehicleController
CreateVehicleController ---.> Repositories
CreateVehicleController ----.>Vehicle
Repositories -> Repositories : instance
Repositories -> VehicleRepository
CreateVehicleController -> VehicleRepository
VehicleRepository --> Vehicle



'Organization -- VehicleRepository
@enduml
