@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class AssignTeamUI {
}

class AssignTeamController {
    + AssignTeamController(employeeRepository, taskRepository, notificationService)
    + assignTeam(employees, task)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getEmployeeRepository()
    + getTaskRepository()
    + getAuthenticationRepository()
}

class AuthenticationRepository {
    + getCurrentUserSession()
}

class UserSession {
    + isLoggedInWithRole()
    + getUserId()
}

class EmployeeRepository {
    + getEmployeesByOrganization(organization)
}

class OrganizationRepository {
    + getOrganizationByUserEmail(email)
}

class Organization {
    - String name
    - String vatNumber
    - String phone
    - String email
    - Address postalAddress
    - validateSkill(skill)
    + Organization(name, vatNumber, webSite, phone, email, postalAddress)
    - getUserByEmail(email)
}

class TaskRepository {
    + getTask(taskId)
}

class Task {
    - String taskId
    - String description
    - List<Employee> assignedEmployees
    + assignTeam(employees)
    + addTeam(employees)
}

class NotificationService {
    + notifyTeamAssignment(employees, task)
}

class Employee {
    - String name
    - String email
    + sendNotification()
}



Repositories -> Repositories : instance
AssignTeamUI .> AssignTeamController
AssignTeamController .> Repositories : repositories
Repositories --> "1" EmployeeRepository
EmployeeRepository --> "*" Employee : employees
AuthenticationRepository -> "1" UserSession : usersession
Repositories --> "1" AuthenticationRepository
Repositories --> "1" TaskRepository
TaskRepository --> "*" Task : tasks
Task "1" --> "*" Employee : assigns
AssignTeamController .> AuthenticationRepository
Employee "1" --> "*" String : contacts
NotificationService .> Employee : notifies

@enduml
