@startuml

hide methods
hide circle

class Teams {
  - numElements
  - skillsNeeded
}

class Tasks {
  - taskCategory
  - toDoList
}

class Agenda {

}

Teams "1"---"0..*" Tasks : assigned to >
Agenda "1"---"1..*" Tasks : organizes >
@enduml