@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "HRM" as ADM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AuthFacade\n:AuthenticationRepository" as AUTHREP
participant "userSession\n:UserSession" as USER
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "employeeRepository\n:EmployeeRepository" as EmployeeRepository
participant "employee\n:Employee" as Employee
participant "skillRepository\n:SkillRepository" as SkillRepository
participant "Skill\n:Skill" as SKILL

activate ADM

    ADM -> UI : List for a collaborator available
    activate UI

    UI -> CTRL : listEmployee()
    activate CTRL

    CTRL -> CTRL : getUserFromSession()

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton
        CTRL <-- RepositorySingleton : Repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getAuthenticationRepository()
        activate PLAT
        CTRL <-- PLAT : AuthenticationRepository()
        deactivate PLAT

        CTRL -> AUTHREP : getCurrentUserSession()
        activate AUTHREP

        AUTHREP -> USER : isLoggedWithRule(HRM)
        activate USER

        AUTHREP <-- USER : "True/False"
        AUTHREP --> USER : getUserId(email)
        AUTHREP <-- USER : userId(email)
        deactivate USER

        CTRL <-- AUTHREP : userId(email)
        deactivate AUTHREP

        CTRL -> CTRL : getOrganizationByUserId(email)

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton
        CTRL <-- RepositorySingleton : Repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getOrganizationRepository()
        activate PLAT
        CTRL <-- PLAT : OrganizationRepository()
        deactivate PLAT

        CTRL -> OrganizationRepository :getOrganizationByUserId(email)
        activate OrganizationRepository
        loop for each organization
        OrganizationRepository -> ORG : anyUserHasId(email)
        activate ORG
        OrganizationRepository <-- ORG : True/False
        deactivate ORG
        end loop

        CTRL <-- OrganizationRepository : organitazion


        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton
        CTRL <-- RepositorySingleton : Repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getEmployeeRepository()
        activate PLAT
        CTRL <-- PLAT : EmployeeRepository()
        deactivate PLAT

        CTRL -> EmployeeRepository : listEmployee()
        activate EmployeeRepository
        CTRL <-- EmployeeRepository : listEmployee
        deactivate EmployeeRepository

        UI <- CTRL: listEmployee


    UI --> ADM : Shows list of collaborators
    deactivate UI

    ADM -> UI : Choose collaborator
    activate UI

        UI -> SkillRepository : getSkillById(skillId: String): Skill
        activate SkillRepository
        UI <-- SkillRepository : listSkill
        deactivate EmployeeRepository

    UI --> ADM : Shows skills list, asks to select one or more
    deactivate UI

    ADM -> UI : Selects one or more skills
    activate UI

    UI --> ADM : Shows all data and requests confirmation
    deactivate UI

    ADM -> UI : Confirms collaborator and skill assigned
    deactivate UI

    UI -> CTRL : assignSkillToTeamMember(employeeId, skillId)

    CTRL -> Employee: createTeamMember()
        activate Employee

        activate Employee
        Employee -> Employee: addTeamMember(TeamMember)
        Employee -> Employee: validateTeamMember(TeamMember)

        deactivate Employee

        Employee --> Employee
        Employee --> Employee
        deactivate Employee

        Employee --> CTRL : TeamMember

        deactivate Employee

        CTRL --> UI: TeamMember
        deactivate CTRL
        UI --> ADM: Displays operation success
        deactivate UI




deactivate ADM









@enduml