@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


skinparam classAttributeIconSize 0

left to right direction

hide circle
hide methods

title "US003 - Create a collaborator" Domain Model

class TeamMember {
   - name
   - birthdate
   - admission date
   - address
   - contact info
   - ID doc type
   - ID document number
   - Taxpayer ID
}

class HRM {
}

class Job {
  - name
}

HRM "1"---"1.." TeamMember: manages >
TeamMember "1"---"1" Job: assignes >

@enduml