@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Human Resources\nManager" as HRManager
participant ":System" as System

activate HRManager

HRManager -> System : Requests team generation for a task
activate System

    System --> HRManager : Requests for data(skills needed, max size of the team)
    deactivate System

    HRManager -> System : Provides data
    activate System

    System --> HRManager : Confirms data reception and presents options (Approve, Rejet)
    deactivate System

HRManager -> System : Submits selection (Approve/Reject)
activate System

alt Approve
    System --> HRManager : Confirms team approval
else Reject
    System --> HRManager : Declines team approval
end

deactivate System

@enduml